---
title: "research"
output: html_document
date: '2022-05-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA,
                      cache = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(tinytex)
library(rgdal)
library(broom)
library(sf)
library(gganimate)
library(transformr)
```


# Analysis

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# read data
daily_caloric_supply <- read_csv("Data/daily-caloric-supply-derived-from-carbohydrates-protein-and-fat.csv")
dietary_compositions <- read_csv("Data/dietary-compositions-by-commodity-group.csv")
overweight_calories <- read_csv("Data/share-of-adult-men-overweight-or-obese-vs-daily-supply-of-calories.csv")
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# data wrangling
daily_caloric_supply <- daily_caloric_supply %>%
  rename_all(str_remove, pattern = "\\(FAO.+\\)") %>%
  select(-Code)

dietary_compositions <- dietary_compositions %>%
  rename_all(str_remove, pattern = "\\(FAO.+\\)") %>%
  select(-Code)
```


```{r fig-1, echo = FALSE, message = FALSE, warning = FALSE, out.width = '75%', fig.align = "center", fig.width = 8, fig.cap ="Kilocalories per Person per Day in Australia"}
# data figure1
figure1 <- dietary_compositions %>% 
  filter(Entity == 'Australia') %>% 
  pivot_longer(cols = -c(Entity,Year),
               names_to = 'Variable',
               values_to = 'Value') %>% 
  ggplot(aes(x = Year,
             y = Value,
             fill = Variable)) +
  geom_area(color = 'white') +
  scale_fill_viridis_d() +
  labs(y = 'Kilocalories per Person per Day',
       title = 'Kilocalories per Person per Day in Australia') +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        text = element_text(size = 8)) +
  transition_reveal(Year)

figure1
animate(figure1,
        res = 300,
        width = 2000,
        height = 1125,
        renderer = gifski_renderer())
anim_save("figure1.gif")
```


# Data Explanation



```{r fig-2, echo = FALSE, message = FALSE, warning = FALSE, out.width = '75%', fig.align = "center", fig.width = 8, fig.cap ="Year: {closest_state}"}
# read world map data
world <- readOGR(dsn = 'World_Countries_(Generalized)/.')
world_shp <- world %>% 
  st_as_sf()
world_data <- daily_caloric_supply %>%
  select(Entity, Year, `Calories from animal protein `) %>%
  merge(world_shp,
        by.x = "Entity",
        by.y = "COUNTRY") %>% 
  st_as_sf()

# data figure2
figure2 = world_data %>%
  ggplot(aes(fill = `Calories from animal protein `)) +
  geom_sf(colour = NA) +
  labs(x = 'Longitude',
       y = 'Latitude',
       title = '  Year: {closest_state}') +
  scale_fill_viridis_c(na.value = 'grey') +
  theme_void() +
  theme(legend.position = 'bottom') +
  transition_states(states = Year)
figure2
animate(figure2,
        res = 300,
        width = 2000,
        height = 1125)
anim_save('figure2.gif')
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# data wrangling
by_country <- overweight_calories %>% 
  rename('caloric_supply' = 'Daily caloric supply (OWID based on UN FAO & historical sources)',
         'Overweight' = 'Overweight or Obese (NCDRisC (2017))') %>% 
  select(Entity, Year, caloric_supply, Overweight) %>%
  filter(Entity %in% c("Australia", "China",
                       "United States", "United Kingdom",
                       "South Africa", "Brazil"),
         Year >= 2000) %>%
  drop_na() %>%
  group_by(Entity)%>%
  nest()
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# linear models
fit_lm <- function(x){
  lm(Overweight~caloric_supply, data = x)
}
mapped_lm <- map(by_country$data, fit_lm)
```


```{r, residuals plots}
library(ggResidpanel)
resid_panel(mapped_lm[[1]], plots = "all")
resid_panel(mapped_lm[[2]], plots = "all")
resid_panel(mapped_lm[[3]], plots = "all")
resid_panel(mapped_lm[[4]], plots = "all")
resid_panel(mapped_lm[[5]], plots = "all")
resid_panel(mapped_lm[[6]], plots = "all")
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Intercept and Slope
rbind(coef(mapped_lm[[1]]),
      coef(mapped_lm[[2]]),
      coef(mapped_lm[[3]]),
      coef(mapped_lm[[4]]),
      coef(mapped_lm[[5]]),
      coef(mapped_lm[[6]])) %>%
  as.data.frame() %>%
  mutate(Country = c("Australia", "Brazil", "China", 
                     "South Africa", "United Kingdom", "United States")) %>%
  rename(Intercept = "(Intercept)",
         Slope = "caloric_supply") %>%
  select(Country, Intercept, Slope)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(data.table)
Australia_lm_summary <- glance(mapped_lm[[1]])
Brazil_lm_summary <- glance(mapped_lm[[2]])
China_lm_summary <- glance(mapped_lm[[3]])
South_Africa_lm_summary <- glance(mapped_lm[[4]])
United_Kingdom_lm_summary <- glance(mapped_lm[[5]])
United_States_lm_summary <- glance(mapped_lm[[6]])

summary <- list(Australia_lm_summary, Brazil_lm_summary, China_lm_summary, 
                South_Africa_lm_summary, United_Kingdom_lm_summary, United_States_lm_summary) %>%
  rbindlist(use.names = TRUE) %>%
  mutate(Country = c("Australia", "Brazil", "China",
                     "South_Africa", "United_Kingdom", "United States")) %>%
  select(Country, r.squared, AIC, BIC) 
```


```{r table, echo = FALSE, message = FALSE, warning = FALSE}
Table1 = summary
knitr::kable(Table1, booktabs = TRUE, "html",
             caption = "Goodness_of_fit_measures") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```